MvcUI/Areas/YoneticiStation/Controllers/AdminHomeController.cs
using System.Web.Mvc;
using MvcUI.Models.ViewModels;

namespace MvcUI.Areas.YoneticiStation.Controllers
{
    [_SessionControl]
    public class AdminHomeController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            DashViewModel dm=new DashViewModel();
            return View(dm);
        }
    }
}

MvcUI/Areas/YoneticiStation/Controllers/MenuController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MvcUI.Models;
using MvcUI.Models.Entities;

namespace MvcUI.Areas.YoneticiStation.Controllers
{
    public class MenuController : Controller
    {
        private List<Menus> GetMenuList()
        {
            List<Menus> menuList = new List<Menus>();
            using (var db = new BSZContext())
            {
                foreach (var menu in db.menus.OrderBy(x => x.MenuOrder))
                {
                    menuList.Add(new Menus
                    {
                        MenuID = menu.MenuID,
                        MenuParentID = menu.MenuParentID,
                        MenuName = menu.MenuName,
                        MenuOrder = menu.MenuOrder,
                        MenuUrl = menu.MenuUrl
                    });
                }
                return menuList;
            }

        }

        public ActionResult Index()
        {
            return View(GetMenuList());
        }

        public ActionResult MenuAdd()
        {
            return View();
        }

        [HttpPost]
        public ActionResult MenuAdd(Menus menu)
        {
            using (var db = new BSZContext())
            {
                db.menus.Add(menu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        public ActionResult MenuUpdate(int id)
        {
            using (var db = new BSZContext())
            {
                var selectedMenu = db.menus.Where(m => m.MenuID == id).FirstOrDefault();
                return View(selectedMenu);
            }
        }

        [HttpPost]
        public ActionResult MenuUpdate(Menus menu, int id)
        {
            using (var db = new BSZContext())
            {
                var selectedMenu = db.menus.Where(m => m.MenuID == id).FirstOrDefault();
                selectedMenu.MenuName = menu.MenuName;
                selectedMenu.MenuOrder = menu.MenuOrder;
                selectedMenu.MenuParentID = menu.MenuParentID;
                selectedMenu.MenuUrl = menu.MenuUrl;
                UpdateModel(selectedMenu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

        }
        
        public ActionResult MenuDelete(int id)
        {
            using (var db = new BSZContext())
            {
                var selectedMenu = db.menus.Where(m => m.MenuID == id).FirstOrDefault();
                db.menus.Remove(selectedMenu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
        }



    }
}

MvcUI/Areas/YoneticiStation/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcUI.Models;
using MvcUI.Models.Entities;

namespace MvcUI.Areas.YoneticiStation.Controllers
{
    public class ProductController : Controller
    {
        private List<Products> GetProductList()
        {
            List<Products> productList = new List<Products>();
            using (var db = new BSZContext())
            {
                foreach (var products in db.products)
                {
                    productList.Add(new Products
                    {
                        ProductID = products.ProductID,
                        ProductBarcode = products.ProductBarcode,
                        ProductBrand = products.ProductBrand,
                        ProductText = products.ProductText,
                        ProductInfo = products.ProductInfo,
                        ProductImage1 = products.ProductImage1,
                        ProductImage2 = products.ProductImage2,
                        ProductImage3 = products.ProductImage3,
                        ProductImage4 = products.ProductImage4
                    });
                }
                return productList;
            }

        }

        public ActionResult Index()
        {
            return View(GetProductList());
        }

        public ActionResult ProductAdd()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ProductAdd(Products products, HttpPostedFileBase productImage1, HttpPostedFileBase productImage2, HttpPostedFileBase productImage3, HttpPostedFileBase productImage4)
        {
            FileInfo fi;
            using (var db = new BSZContext())
            {
                if (productImage1 != null)
                {
                    fi = new FileInfo(productImage1.FileName);
                    if (fi.Extension.ToLower() == ".jpg" || fi.Extension.ToLower() == ".png" ||
                        fi.Extension.ToLower() == ".jpeg")
                    {
                        string img1Path = products.ProductBarcode + "-1" + fi.Extension;
                        var img1UploadPath = Path.Combine(Server.MapPath(Url.Content("~/Contents/img/products/" + products.ProductBarcode + "/" + img1Path)));
                        if (!Directory.Exists(Server.MapPath(Url.Content("~/Contents/img/products/" + products.ProductBarcode))))
                        {
                            Directory.CreateDirectory(Server.MapPath(Url.Content("~/Contents/img/products/" + products.ProductBarcode)));
                        }
                        else
                        {
                            Directory.Delete(Server.MapPath(Url.Content("~/Contents/img/products/" + products.ProductBarcode)),true);
                        }
                        productImage1.SaveAs(img1UploadPath);
                        products.ProductImage1 = img1Path;
                    }


                    if (productImage2 != null)
                    {
                        if (fi.Extension.ToLower() == ".jpg" || fi.Extension.ToLower() == ".png" ||
                            fi.Extension.ToLower() == ".jpeg")
                        {
                            fi = new FileInfo(productImage2.FileName);
                            string img2Path = products.ProductBarcode + "-2" + fi.Extension;
                            var img2UploadPath = Path.Combine(Server.MapPath(
                                Url.Content("~/Contents/img/products/" + products.ProductBarcode + "/" + img2Path)));
                            productImage2.SaveAs(img2UploadPath);
                            products.ProductImage2 = img2Path;
                        }
                    }

                    if (productImage3 != null)
                    {
                        fi = new FileInfo(productImage3.FileName);
                        if (fi.Extension.ToLower() == ".jpg" || fi.Extension.ToLower() == ".png" ||
                            fi.Extension.ToLower() == ".jpeg")
                        {
                            string img3Path = products.ProductBarcode + "-3" + fi.Extension;
                            var img3UploadPath = Path.Combine(Server.MapPath(
                                Url.Content("~/Contents/img/products/" + products.ProductBarcode + "/" + img3Path)));
                            productImage3.SaveAs(img3UploadPath);
                            products.ProductImage3 = img3Path;
                        }
                    }

                    if (productImage4 != null)
                    {
                        fi = new FileInfo(productImage4.FileName);
                        if (fi.Extension.ToLower() == ".jpg" || fi.Extension.ToLower() == ".png" ||
                            fi.Extension.ToLower() == ".jpeg")
                        {
                            string img4Path = products.ProductBarcode + "-4" + fi.Extension;
                            var img4UploadPath = Path.Combine(Server.MapPath(
                                Url.Content("~/Contents/img/products/" + products.ProductBarcode + "/" + img4Path)));
                            productImage4.SaveAs(img4UploadPath);
                            products.ProductImage4 = img4Path;
                        }
                    }
                    db.products.Add(products);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("ProductAdd");
                }
            }
        }

        public ActionResult ProductUpdate(int id)
        {
            using (var db = new BSZContext())
            {
                var selectedProduct = db.products.Where(m => m.ProductID == id).FirstOrDefault();
                return View(selectedProduct);
            }
        }

        [HttpPost]
        public ActionResult ProductUpdate(Products product, int id, HttpPostedFileBase image1, HttpPostedFileBase image2, HttpPostedFileBase image3, HttpPostedFileBase image4)
        {
            FileInfo fi;
            using (var db = new BSZContext())
            {
                var selectedProduct = db.products.Where(m => m.ProductID == id).FirstOrDefault();
                selectedProduct.ProductBrand = product.ProductBrand;
                selectedProduct.ProductText = product.ProductText;
                selectedProduct.ProductInfo = product.ProductInfo;

                if (selectedProduct.ProductBarcode != product.ProductBarcode)
                {
                    if (Directory.Exists(
                        Server.MapPath(Url.Content("~/Contents/img/products/" + selectedProduct.ProductBarcode))))
                    {
                        Directory.CreateDirectory(
                            Server.MapPath(
                                Url.Content("~/Contents/img/products/" + product.ProductBarcode)));

                        string from1 =
                               Server.MapPath(
                                   Url.Content("~/Contents/img/products/" + selectedProduct.ProductBarcode + "/" + selectedProduct.ProductImage1));
                        string to1 =
                            Server.MapPath(
                                Url.Content("~/Contents/img/products/" + product.ProductBarcode + "/" + product.ProductBarcode + "-1." +selectedProduct.ProductImage1.Split('.').Last()));
                        System.IO.File.Move(from1, to1);
                        selectedProduct.ProductImage1 = product.ProductBarcode + "-1." + selectedProduct.ProductImage1.Split('.').Last();

                        string from2 =
                            Server.MapPath(
                                Url.Content("~/Contents/img/products/" + selectedProduct.ProductBarcode + "/" + selectedProduct.ProductImage2));
                        string to2 =
                            Server.MapPath(
                                Url.Content("~/Contents/img/products/" + product.ProductBarcode + "/" + product.ProductBarcode + "-2." + selectedProduct.ProductImage2.Split('.').Last()));
                        System.IO.File.Move(from2, to2);
                        selectedProduct.ProductImage2 = product.ProductBarcode + "-2." + selectedProduct.ProductImage2.Split('.').Last();

                        string from3 =
                            Server.MapPath(
                                Url.Content("~/Contents/img/products/" + selectedProduct.ProductBarcode + "/" + selectedProduct.ProductImage3));
                        string to3 =
                            Server.MapPath(
                                Url.Content("~/Contents/img/products/" + product.ProductBarcode + "/" + product.ProductBarcode + "-3." + selectedProduct.ProductImage3.Split('.').Last()));
                        System.IO.File.Move(from3, to3);
                        selectedProduct.ProductImage3 = product.ProductBarcode + "-3." + selectedProduct.ProductImage3.Split('.').Last();

                        string from4 =
                            Server.MapPath(
                                Url.Content("~/Contents/img/products/" + selectedProduct.ProductBarcode + "/" + selectedProduct.ProductImage4));
                        string to4 =
                            Server.MapPath(
                                Url.Content("~/Contents/img/products/" + product.ProductBarcode + "/" + product.ProductBarcode + "-4." + selectedProduct.ProductImage4.Split('.').Last()));
                        System.IO.File.Move(from4, to4);
                        selectedProduct.ProductImage4 = product.ProductBarcode + "-4." + selectedProduct.ProductImage4.Split('.').Last();

                        Directory.Delete(
                            Server.MapPath(
                                Url.Content("~/Contents/img/products/" + selectedProduct.ProductBarcode)), true);

MvcUI/Areas/YoneticiStation/Controllers/SettingsController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using MvcUI.Models;
using MvcUI.Models.Entities;

namespace MvcUI.Areas.YoneticiStation.Controllers
{
    public class SettingsController : Controller
    {
        public ActionResult Index()
        {
            Settings settings;
            Contact contact;
            using (var db = new BSZContext())
            {
                var set = db.settings.FirstOrDefault();

                settings = new Settings
                {
                    copyright = set.copyright,
                    description = set.description,
                    email = set.email,
                    favicon = set.favicon,
                    keywords = set.keywords,
                    logo = set.logo,
                    mailpass = set.mailpass,
                    mailport = set.mailport,
                    mailsendfrom = set.mailsendfrom,
                    mailserver = set.mailserver,
                    mailuser = set.mailuser,
                    prices_isactive = set.prices_isactive,
                    title = set.title
                };

                var cont = db.contact.FirstOrDefault();

                contact = new Contact
                {
                    Email = set.email,
                    About_text = cont.About_text,
                    Address = cont.Address,
                    Facebook = cont.Facebook,
                    Google_plus = cont.Google_plus,
                    Instagram = cont.Instagram,
                    Phone = cont.Phone
                };
                return View(Tuple.Create(settings, contact));
            }

        }


        [HttpPost]
        public ActionResult UpdateSettings([Bind(Prefix = "Item1")]Settings _settings, [Bind(Prefix = "Item2")]Contact _contact)
        {
            try
            {
                using (var db = new BSZContext())
                {
                    var settings = db.settings.FirstOrDefault();
                    var contact = db.contact.FirstOrDefault();

                    settings.copyright = _settings.copyright;
                    settings.description = _settings.description;
                    settings.email = _settings.email;
                    settings.keywords = _settings.keywords;
                    settings.mailpass = _settings.mailpass;
                    settings.mailport = _settings.mailport;
                    settings.mailsendfrom = _settings.mailsendfrom;
                    settings.mailserver = _settings.mailserver;
                    settings.mailuser = _settings.mailuser;
                    settings.prices_isactive = _settings.prices_isactive;
                    settings.title = _settings.title;

                    contact.Email = settings.email;
                    contact.About_text = _contact.About_text;
                    contact.Address = _contact.Address;
                    contact.Facebook = _contact.Facebook;
                    contact.Google_plus = _contact.Google_plus;
                    contact.Instagram = _contact.Instagram;
                    contact.Phone = _contact.Phone;

                    UpdateModel(settings);
                    UpdateModel(contact);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception hh)
            {
                return RedirectToAction("Index");
            }
        }

    }
}

MvcUI/Areas/YoneticiStation/Controllers/SharedController.cs
using System.Web.Mvc;

namespace MvcUI.Areas.YoneticiStation.Controllers
{
    public class SharedController : Controller
    {
        public ActionResult _Header()
        {
            return PartialView();
        }
        public ActionResult _Sidebar()
        {
            return PartialView();
        }
    }
}

MvcUI/Areas/YoneticiStation/Views/Shared/_Footer.cshtml
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Admin LTE Version</b> 2.4.0
    </div>
    <strong>Copyright &copy; @DateTime.Now.Year <a href="https://suleymanbabaoglu.com.tr">SB</a>.</strong> All Rights Reserved.
</footer>

MvcUI/Areas/YoneticiStation/Views/Shared/_Header.cshtml
<header class="main-header">
    <!-- Logo -->
    <a href="~/YoneticiStation/AdminHome" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>LB</b></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>LolliBaby</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <div class="navbar-custom-menu">

            @using (Html.BeginForm("LogOff", "Login", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <button type="submit" class="btn btn-danger" style="margin-top: 10%; margin-right: 10px;">
                    <i class="fa fa-power-off"></i> <span>Log Off</span>
                </button>
            }
        </div>
        <div style="float: right">
            <a href="~/" target="_blank" class="btn btn-warning" style="margin-top: 5%;margin-right: 10px;">
                <i class="fa fa-home"></i> <span>LolliBaby HomePage</span>
            </a>
        </div>
       
    </nav>
</header>

MvcUI/Areas/YoneticiStation/Views/Shared/_Sidebar.cshtml
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->

        <div class="user-panel">
            <div class="pull-left info">
                <p></p>
                <p></p>
            </div>
            <div class="pull-left image" style="height:30px">

            </div>
        </div>


        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li>
                <a href="@Url.Action("Index", "AdminHome", new { area = "YoneticiStation" })">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index","Settings", new { area = "YoneticiStation" })">
                    <i class="fa fa-gears"></i> <span>Settings</span>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-gear"></i>
                    <span>Website Management</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li>
                        <a href="@Url.Action("Index","Product", new { area = "YoneticiStation" })">
                            <i class="fa fa-product-hunt"></i> <span>Products</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Menu", new {area = "YoneticiStation"})">
                            <i class="fa fa-navicon"></i> <span>Menus</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Settings", new {area = "YoneticiStation"})">
                            <i class="fa fa-caret-square-o-right"></i> <span>Sliders</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Settings", new {area = "YoneticiStation"})">
                            <i class="fa fa-cubes"></i> <span>Features</span>
                        </a>
                    </li>

                </ul>

            </li>
            

        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

MvcUI/Areas/YoneticiStation/Views/Shared/_mainView.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="icon" href="@Url.Content("~/Contents/img/favicon.png")" sizes="32x32" type="image/png" />
    <title>Management Panel</title>
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    @Styles.Render("~/AdminCss")
    <link rel="stylesheet" href="~/Contents/AContent/bower_components/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/Contents/AContent/bower_components/Ionicons/css/ionicons.min.css" />



</head>
<body class="hold-transition skin-blue sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">

        @Html.Action("_Header", "Shared")
        <!-- =============================================== -->
        <!-- Left side column. contains the sidebar -->
        @Html.Action("_Sidebar", "Shared")
        <!-- =============================================== -->
        <!-- Content Wrapper. Contains page content -->
        @RenderBody()
        <!-- /.content-wrapper -->

        @Html.Partial("_Footer")

        <!-- Add the sidebar's background. This div must be placed
             immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->

    @Scripts.Render("~/AdminJs")
    <script>
        $(document).ready(function () {
            $('.sidebar-menu').tree()
        })
    </script>
    <script>

        $(document).ready(function () {
            $('#example2').DataTable({
                'paging': true,
                'lengthChange': false,
                'searching': false,
                'ordering': true,
                'info': true,
                'autoWidth': false
            })
        })
    </script>
</body>
</html>